### PR TITLE
Update package.json Fixed all Moralis errors 

### PR DESCRIPTION
**Pull request by akashgreninja**
I have fixed some issues of Moralis Package that was updated some days ago and users were getting errors such as 

`module not found: can't resolve 'moralis-v1'`
`module not found: can't resolve '@walletconnect/modal'`
`Module not found: Can't resolve '@walletconnect/ethereum-provider' in \node_modules\moralis-v1\lib\browser\Web3Connector'`

This pull request must fix issues given below :
#40 
#44 
#38 

@PatrickAlphaC Check this asap as this is the newest versions which will make the code work

### CODE REVIEW

**Comment by PatrickAlphaC** [comment]
Thanks for this! Could you adjust the formatting? The PR shows that you updated the whole file, when it looks like you probably only updated a few versions?

**Comment by akashgreninja** [comment]
@PatrickAlphaC check it once i have changed it

**Comment by PatrickAlphaC** [comment]
Screenshot 2023-07-29 at 10 17 02 PM
Still shows the whole file. 

It might be easier to reset your branch to this one, make the changes and select "save without formatting"

**Comment by akashgreninja** [comment]
the moralis package got an update some days ago so the extra packages are because of that 

ill do what you just said and make the necessary changes

**Comment by akashgreninja** [comment]
can you please check #46

**Pull request closed without merging**
